DELETE  https://fluffy-iris-selenium.glitch.me/XeDaGiao/10
###
POST  https://script.google.com/macros/s/AKfycbyLjKopyyQbvogd9WNWVIVJYYnGxrQNwQ-coP1cTVT1vXPzf-VNlXV8nhUHzogBm09m/exec

###
POST https://fluffy-iris-selenium.glitch.me/XeDaGiao

{"NhomCV":{["Toàn","Tài","Rôn","Mẫn","Sang","Vinh","Triêng","Lộc","Sang"]}}
####

GET  https://fluffy-iris-selenium.glitch.me/User
####

POST https://fluffy-iris-selenium.glitch.me/User
  {
    "user":"Boygl34",
    "useName":"Võ Chính Trực",
    "PhanQuyen":"admin",
    "BoPhan":"Dịch Vụ"}