DELETE  https://fluffy-iris-selenium.glitch.me/XeTrongXuong/198
###
PATCH  https://fluffy-iris-selenium.glitch.me/XeTrongXuong/167
{
  "MaSo":"TVT20220629_72A-325.22"
  }
###

GET  https://fluffy-iris-selenium.glitch.me/XeTrongXuong?MaSo=


###
GET  https://fluffy-iris-selenium.glitch.me/XeTrongXuong?BienSoXe=72A-255.90

