DELETE  https://fluffy-iris-selenium.glitch.me/XeTrongXuong/195
###
PATCH  https://fluffy-iris-selenium.glitch.me/XeTrongXuong/167
{
  "MaSo":"TVT20220629_72A-325.22"
  }
###
POST https://fluffy-iris-selenium.glitch.me/XeDaGiao

{"NhomCV":{["Toàn","Tài","Rôn","Mẫn","Sang","Vinh","Triêng","Lộc","Sang"]}}
####

GET  https://fluffy-iris-selenium.glitch.me/User
####

POST https://fluffy-iris-selenium.glitch.me/User
  {
    "user":"Boygl34",
    "useName":"Võ Chính Trực",
    "PhanQuyen":"admin",
    "BoPhan":"Dịch Vụ"}